StudentPortal/Models/ErrorViewModel.cs
using System;

namespace StudentPortal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudentPortal/Models/NotificationVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using StudentPortal.Models.Dtos.Notification;

namespace StudentPortal.Models
{
    public class NotificationVm
    {
        public NotificationVm()
        {
            NotificationDto = new NotificationDto();
        }
        public IFormFile TimeTableFile { get; set; }
        public NotificationDto NotificationDto { get; set; }


    }
}

StudentPortal/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StudentPortal.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Auth()
        {
            return View();
        }
    }
}

StudentPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StudentPortal.Models;

namespace StudentPortal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

StudentPortal/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudentPortal.Models;
using StudentPortal.Models.Dtos.Notification;
using StudentPortal.Models.Models;
using StudentPortal.Utilities;
using Trough.Utilities;

namespace StudentPortal.Controllers
{
    public class NotificationController : Controller
    {
        private readonly stdportalContext _context;

        public NotificationController(stdportalContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult VisitorNotification()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> VisitorNotification(NotificationDto model)
        {
            NotificationsHandler.SendPushNotification("/topics/visitor", model.Message, model.Title, model.Type);
            var notification = new Notifications()
            {
                Title = model.Title,
                Type = model.Type,
                Message = model.Message,
                TargetScreen = model.Type,
                IsImportant = model.IsImportant,
                IsVisitorNotification = true
            };
            await _context.Notifications.AddAsync(notification);
            await _context.SaveChangesAsync();
            return Json(true);
        }

        [HttpPost]
        public async Task<IActionResult> StudentNotification(NotificationVm model)
        {
            var url = "";
            //NotificationsHandler.SendPushNotification("/topics/student", model.Message, model.Title, model.Type);
            if (!(model.TimeTableFile is null))
            {
                url = await CommonMethods.UploadFile(model.TimeTableFile);
            }
            var notification = new Notifications()
            {
                Title = model.NotificationDto.Title,
                Type = model.NotificationDto.Type,
                Message = model.NotificationDto.Message,
                TargetScreen = model.NotificationDto.Type,
                IsAllStudentNotification = true
            };
            if (!(string.IsNullOrEmpty(url)))
            {
                notification.TimeTable.Add(new TimeTable()
                {
                    CreatedDate = DateTime.Now,
                    FileUrl = url,
                    IsActive = true
                });
            }

            try
            {
                await _context.Notifications.AddAsync(notification);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {

            }
            return Json(true);
        }
        public IActionResult AllStudentNotification()
        {
            return View();
        }
        public IActionResult SpecificStudentNotification()
        {
            return View();
        }
        public IActionResult BatchNotification()
        {
            return View();
        }
        public IActionResult SectionNotification()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Uploads(string id)
        {
            var fileDetail = "";
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot") + "/Uploads/"+id;
            if (fileDetail != null)
            {
                System.Net.Mime.ContentDisposition cd = new System.Net.Mime.ContentDisposition
                {
                    FileName = "Test.pdf",
                    Inline = false
                };
                Response.Headers.Add("Content-Disposition", cd.ToString());

                //get physical path
                var fileReadPath = filePath;

                var file = System.IO.File.OpenRead(fileReadPath);
                return File(file, "APPLICATION/octet-stream","test1.pdf");
            }
            //else
            //{
            //    return StatusCode(404);
            //}

            return View("AllStudentNotification");
        }
    }
}

StudentPortal/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StudentPortal.Controllers
{
    public class ReportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StudentPortal/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StudentPortal.Controllers
{
    public class ResultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddNewResult()
        {
            return View();
        }
    }
}

StudentPortal/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StudentPortal.Controllers
{
    public class SubjectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddSubject()
        {
            return View();
        }
    }
}

StudentPortal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StudentPortal/Views/Notification/AllStudentNotification.cshtml
@model StudentPortal.Models.NotificationVm
@{
    ViewData["Title"] = "AllStudentNotification";
    Layout = "~/Views/Shared/_MainLayout/_MainLayout.cshtml";
}
@section styles
{
    <link href="~/Assests/node_modules/dropify/dist/css/dropify.min.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Assests/node_modules/dropify/dist/js/dropify.min.js"></script>
    <script>
        $('.dropify').dropify();
        $("form#Students").submit(function (e) {
            debugger;
            e.preventDefault();
            var flag = $("#Students").valid();
            if (!(flag)) {
                e.preventDefault();
            } else {
                //showLoader();
                var formData = new FormData(this);
                $.ajax({
                    url: '@Url.Action("StudentNotification", "Notification")',
                    type: 'POST',
                    data: formData,
                    success: function(data) {
                        onSaveUserSuccess(data);
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });
            }
        });

        function onSaveUserSuccess(data) {
            // HideLoader();
            alert("success");
        }

        $('.time-table-file').hide();
        function showFile() {
            $('.time-table-file').hide();
            if ($("#NotificationDto_Type").val() === "Time table notice") {
                $('.time-table-file').show();

            }
            
        }
    </script>
}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">All Student</h4>
                <form class="mt-4" id="Students">
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control" asp-for="NotificationDto.Title" aria-describedby="emailHelp" placeholder="Enter Title">
                        <span asp-validation-for="NotificationDto.Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Message</label>
                        <textarea class="form-control" rows="5" asp-for="NotificationDto.Message"></textarea>
                        <span asp-validation-for="NotificationDto.Message" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Select Message Type</label>
                        <select class="form-control custom-select" asp-for="NotificationDto.Type" onchange="showFile()">
                            <option value="" disabled="" selected="" hidden="">Select message type</option>
                            <option value="Fee notice">Fee notice</option>
                            <option value="Holiday notice">Holiday notice</option>
                            <option value="Exams notice">Exams notice</option>
                            <option value="Events notice">Events notice</option>
                            <option value="Result notice">Result notice</option>
                            <option value="Time table notice">Time table notice</option>
                            <option value="Entry test notice">Entry test notice</option>
                            <option value="Admission notice">Admission notice</option>
                            <option value="Others">Others</option>
                        </select>
                        <span asp-validation-for="NotificationDto.Type" class="text-danger"></span>
                    </div>
                    <div class="form-group time-table-file">
                        <label class="card-title">Food Truck Banner</label>
                        @*<label for="input-file-max-fs">You can add a max file size</label>*@
                        <input type="file" asp-for="TimeTableFile" class="dropify" data-max-file-size="5M" data-allowed-file-extensions="xlsx xlsm xlsb pdf doc docx" />
                        <span asp-validation-for="TimeTableFile" class="text-danger"></span>
                    </div>
                    <div class="custom-control custom-checkbox mr-sm-2 mb-3">
                        <input type="checkbox" class="custom-control-input" asp-for="NotificationDto.IsImportant" value="check">
                        <label class="custom-control-label" asp-for="NotificationDto.IsImportant">Is Important?</label>
                    </div>
                    @*<iframe src="~/Uploads/Test.pdf"></iframe>*@
                    <button type="submit" class="btn float-right btn-primary">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>

StudentPortal/Views/Notification/VisitorNotification.cshtml
@model StudentPortal.Models.Dtos.Notification.NotificationDto
@{
    ViewData["Title"] = "VisitorNotification";
    Layout = "~/Views/Shared/_MainLayout/_MainLayout.cshtml";
}

@section scripts{ 
    <script>
        $("form#Visitors").submit(function (e) {
            debugger;
            e.preventDefault();
            var flag = $("#Visitors").valid();
            if (!(flag)) {
                e.preventDefault();
            } else {
                //showLoader();
                var formData = new FormData(this);
                $.ajax({
                    url: '@Url.Action("VisitorNotification", "Notification")',
                    type: 'POST',
                    data: formData,
                    success: function(data) {
                        onSaveUserSuccess(data);
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });
            }
        });



        function onSaveUserSuccess(data) {
           // HideLoader();
           alert("success");
        }
    </script>
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Visitor</h4>
                <form class="mt-4" id="Visitors">
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" class="form-control" asp-for="Title" aria-describedby="emailHelp" placeholder="Enter Title">
                    </div>
                    <div class="form-group">
                        <label>Message</label>
                        <textarea class="form-control" rows="5" asp-for="Message"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Select Message Type</label>
                        <select class="form-control custom-select" asp-for="Type">
                            <option value="" disabled="" selected="" hidden="">Select message type</option>
                            <option value="Fee notice">Fee notice</option>
                            <option value="Holiday notice">Holiday notice</option>
                            <option value="Exams notice">Exams notice</option>
                            <option value="Events notice">Events notice</option>
                            <option value="Result notice">Result notice</option>
                            <option value="Time table notice">Time table notice</option>
                            <option value="Entry test notice">Entry test notice</option>
                            <option value="Admission notice">Admission notice</option>
                            <option value="Others">Others</option>
                        </select>
                    </div>
                    <div class="custom-control custom-checkbox mr-sm-2 mb-3">
                        <input type="checkbox" class="custom-control-input" asp-for="IsImportant" value="check" >
                        <label class="custom-control-label" asp-for="IsImportant">Is Important?</label>
                    </div>
                    <button type="submit" class="btn float-right btn-primary">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>

StudentPortal/Views/Report/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout/_MainLayout.cshtml";
}

@section scripts{
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
    <script>
        $(function () {
            $('#myTable').DataTable();
            var table = $('#example').DataTable({
                "columnDefs": [{
                    "visible": false,
                    "targets": 2
                }],
                "order": [
                    [2, 'asc']
                ],
                "displayLength": 25,
                "drawCallback": function (settings) {
                    var api = this.api();
                    var rows = api.rows({
                        page: 'current'
                    }).nodes();
                    var last = null;
                    api.column(2, {
                        page: 'current'
                    }).data().each(function (group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                            last = group;
                        }
                    });
                }
            });
            // Order by the grouping
            $('#example tbody').on('click', 'tr.group', function () {
                var currentOrder = table.order()[0];
                if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                    table.order([2, 'desc']).draw();
                } else {
                    table.order([2, 'asc']).draw();
                }
            });
            // responsive table
            $('#config-table').DataTable({
                responsive: true
            });
            $('#example23').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
            $('.buttons-copy, .buttons-csv, .buttons-print, .buttons-pdf, .buttons-excel').addClass('btn btn-primary mr-1');
        });

    </script>
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Search Result</h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">

                            <a href="@Url.Action("AddNewResult","Result")" class="btn btn-info d-none d-lg-block m-l-15">
                                <i class="ti-plus"></i> Add New Result
                            </a>
                        </div>
                    </div>
                </div>                <form class="mt-4">
                    <div class="row">
                        <div class="col-6 col-lg-3">
                            <div class="form-group">
                                <label for="Select">Select Class</label>
                                <select class="form-control" id="Select" required="">
                                    <option value="" disabled="" selected="" hidden="">Select class</option>
                                    <option>BSCS</option>
                                    <option>MSCS</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="form-group">
                                <label for="Select">Select Section</label>
                                <select class="form-control" id="Select" required="">
                                    <option value="" disabled="" selected="" hidden="">Select section</option>
                                    <option>A</option>
                                    <option>B</option>
                                    <option>C</option>
                                    <option>E1</option>
                                    <option>E2</option>
                                    <option>Other</option>
                                </select>
                            </div>

                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="form-group">
                                <label for="Select">Select Year</label>
                                <select class="form-control" id="Select" required="">
                                    <option value="" disabled="" selected="" hidden="">Select year</option>
                                    <option>1st year</option>
                                    <option>2nd year</option>
                                    <option>3rd year</option>
                                    <option>4th year</option>
                                </select>
                            </div>

                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="form-group">
                                <label for="Select">Select Batch</label>
                                <select class="form-control" id="Select" required="">
                                    <option value="" disabled="" selected="" hidden="">Select batch</option>
                                    <option>2016-2020</option>
                                    <option>2017-2021</option>
                                    <option>2018-2022</option>
                                    <option>2019-2023</option>
                                    <option>2020-2024</option>
                                    <option>Others</option>
                                </select>
                            </div>

                        </div>
                    </div>

                    <button type="submit" class="btn float-right btn-primary">Search</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Result List</h4>
                    </div>

                </div>
                <div class=" m-t-40">
                    <table id="example23"
                           class="display nowrap table table-hover table-striped table-bordered"
                           cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Students Name</th>
                                <th>Semester</th>
                                <th>Class</th>
                                <th>Mid Term</th>
                                <th>Final</th>
                                <th>Total</th>

                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>Tiger Nixon</td>
                                <td>System Architect</td>
                                <td>Edinburgh</td>
                                <td>61</td>
                                <td>61</td>
                                <td>61</td>

                            </tr>
                            <tr>
                                <td>Garrett Winters</td>
                                <td>Accountant</td>
                                <td>Tokyo</td>
                                <td>63</td>
                                <td>63</td>
                                <td>63</td>

                            </tr>
                            <tr>
                                <td>Ashton Cox</td>
                                <td>Junior Technical Author</td>
                                <td>San Francisco</td>
                                <td>66</td>
                                <td>66</td>
                                <td>66</td>

                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>

StudentPortal/Views/Shared/_MainLayout/_MainLayoutTopBar.cshtml
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="user-pro">
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><img src="../assets/images/users/1.jpg" alt="user-img" class="img-circle"><span class="hide-menu">Mark Jeckson</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="javascript:void(0)"><i class="ti-user"></i> My Profile</a></li>
                        <li><a href="javascript:void(0)"><i class="ti-wallet"></i> My Balance</a></li>
                        <li><a href="javascript:void(0)"><i class="ti-email"></i> Inbox</a></li>
                        <li><a href="javascript:void(0)"><i class="ti-settings"></i> Account Setting</a></li>
                        <li><a href="javascript:void(0)"><i class="fa fa-power-off"></i> Logout</a></li>
                    </ul>
                </li>
                <li class="nav-small-cap">--- PERSONAL</li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="icon-speedometer"></i><span class="hide-menu">Dashboard <span class="badge badge-pill badge-cyan ml-auto">4</span></span></a>
                    @*<ul aria-expanded="false" class="collapse">
                <li><a href="index.html">Minimal </a></li>
                <li><a href="index2.html">Analytical</a></li>
                <li><a href="index3.html">Demographical</a></li>
                <li><a href="index4.html">Modern</a></li>
            </ul>*@
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="ti-bell"></i><span class="hide-menu">Notification</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="@Url.Action("VisitorNotification","Notification")">Visitor</a></li>
                        <li>
                            <a href="javascript:void(0)" class="has-arrow">Student <span class="badge badge-pill badge-success pull-right"></span></a>
                            <ul aria-expanded="false" class="collapse">
                                <li><a href="@Url.Action("AllStudentNotification","Notification")">All Student</a></li>
                                <li><a href="@Url.Action("SpecificStudentNotification","Notification")">Specific Student</a></li>

                            </ul>
                        </li>
                        <li><a href="@Url.Action("BatchNotification","Notification")">Batch</a></li>
                        <li><a href="@Url.Action("SectionNotification","Notification")">Section</a></li>

                    </ul>
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="ti-bookmark"></i><span class="hide-menu">Subject</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="@Url.Action("Index","Subject")">All Subject</a></li>

                        <li><a href="@Url.Action("AddSubject","Subject")">Add New Subject</a></li>

                    </ul>
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="ti-book"></i><span class="hide-menu">Result</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="@Url.Action("Index","Result")">Result List</a></li>

                        <li><a href="@Url.Action("AddNewResult","Result")">Add New Result</a></li>

                    </ul>
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false"><i class="ti-pencil"></i><span class="hide-menu">Report</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="@Url.Action("Index","Report")">Result List</a></li>

                        <li><a href="@Url.Action("AddNewResult","Result")">Add New Result</a></li>

                    </ul>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>

StudentPortal/Views/Subject/AddSubject.cshtml
@{
    ViewData["Title"] = "AddSubject";
    Layout = "~/Views/Shared/_MainLayout/_MainLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Add New Subject</h4>
                <form class="mt-4">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Subject Name</label>
                        <input type="text" class="form-control" id="exampleInputEmail1"  placeholder="Enter Subject Name">
                    </div>
                    <div class="form-group">
                        <label for="Professor">Professor Name</label>
                        <input type="text" class="form-control" id="Professor"  placeholder="Enter Professor Name">
                    </div>
                    <div class="form-group">
                        <label>Select Semester</label>
                        <select class="form-control custom-select">
                            <option value="" disabled="" selected="" hidden="">Select message type</option>
                            <option>Fee notice</option>
                            <option>Holiday notice</option>
                            <option>Exams notice</option>
                            <option>Events notice</option>
                            <option>Result notice</option>
                            <option>Time table notice</option>
                            <option>Entry test notice</option>
                            <option>Admission notice</option>
                            <option>Others</option>
                        </select>
                    </div>
                    
                    <button type="submit" class="btn float-right btn-primary">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>